# Manejo de Excepciones

> 1. Usando Try-Catch

    try {
        ... (código prueba)
    } catch(FileNotFoundException e) {
        ... (control de la excepción)
    } catch(<CLASE>Exception e) {
        ... (control de la excepción)
    } catch(Exception e) {
        ... (control de excepciones restantes)
    } finally {
        ... (código finalizador)
    }

> 2. Delegar el manejo de las excepciones (desencadenamos la excepción)

    public <tipo> <método>() throws <excepción 1>, ..., <excepción n> {
        ... (código capaz de generar una excepción)
    }